# Generated by Django 5.0.2 on 2024-03-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_alter_menu_price_alter_menu_rating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(null=True, upload_to='dishimages'),
        ),
    ]
